### ISSUE TITLE
感謝你的開源精神，能否提供下pyqt4的ui文件？

### ISSUE THREAD

**Issue by cfgrpg** [gw19/TRA-Ticket-Booker#1]
最近剛剛學習pyqt，想直接上pyqt5，程序移植過去好像蠻麻煩，我想有那個ui文件應該會簡單很多！

**Comment by gw19** [comment]
你好，對不起我現在才看到這個 issue。這程式的 ui 都是用程式碼一行一行建構出來的，我有點不太懂你說的 ui 文件是什麼？

**Comment by cfgrpg** [comment]
你好，感謝回復，我以為ui是使用qt designer設計出來的，如果使用qt designer設計出來的就會有ui文件。
